services:
  web:
    image: ghcr.io/penivera/dual-hq:latest
    build: .
    container_name: dual_hq_web
    restart: unless-stopped
    ports:
      - "8010:8010"
    labels:
      - traefik.docker.network=coolify
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SERVER_PORT=8010
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - coolify
    volumes:
      - ./logs:/app/logs

networks:
  coolify:
    external: true
